### ISSUE TITLE
Access violation writing location

### ISSUE THREAD

**Issue by barelief** [bakercp/ofxJSONRPC#7]
exception is thrown when exiting the application (default example):

![VS2012 exception](http://www.ultraimg.com/images/Screenshot135188.png)

System: VS2012, windows 8.1

**Comment by bakercp** [comment]
What branch and oF version?

**Comment by barelief** [comment]
084 stable vs release

**Comment by bakercp** [comment]
I believe this is fixed in the develop branch when using the 0.9.0 / master release.  I'm not supporting 0.8.4 any more as it's got a lot of shutdown problems like this related to static initialization, old versions of Poco, etc.  I'm closing this for now, but please feel free to re-open it if you are still getting this error on the develop branch with 0.9.0!

**Comment by barelief** [comment]
Great. Thanks for the Info.
